### ISSUE TITLE
【ITA連携】パラメータシートに値を直接投入したい

### ISSUE THREAD

**Issue by takeo-e** [exastro-suite/oase#1237]
# 背景
ITA のパラメータシートと連携するためには、メッセージ抽出機能でマッチした文字列をパラメータとして使用できる。
一方で、メッセージ上に無い文字列をパラメータとして連携することはできない。

## 例
ディスク使用量が閾値を超えた場合、ファイルを圧縮するというシナリオの場合、圧縮対象のファイルのパスを変数化しておきパラメータで管理したい。
```yaml
- name: Compress Log file
  community.general.archive:
    src: "{{ VAR_file_path }}/{{ VAR_file_name }}"
    remove: yes
    format: gz
```
現在は、アラートメッセージ上にある文字列のみをパラメータとして抽出するが、メッセージにない文字列でもOASE上で設定した値を直接連携できるようにしたい。

# 受け入れ基準
- ITAに渡すパラメータをメッセージ以外の設定値から連携できること
- 「メッセージ抽出機能」という名前を「パラメータ連携機能」に変更
- 他、検討の余地あり
